# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"unpack_int64_list": "00_utils.ipynb",
         "unpack_bytes_list": "00_utils.ipynb",
         "unpack_sample": "00_utils.ipynb",
         "Reader": "00_utils.ipynb",
         "compression_code": "00_utils.ipynb",
         "path": "01_data.ipynb",
         "path_img": "01_data.ipynb",
         "train_fnames": "01_data.ipynb",
         "test_fnames": "01_data.ipynb",
         "get_items": "01_data.ipynb",
         "data": "01_data.ipynb",
         "get_x": "01_data.ipynb",
         "get_y": "01_data.ipynb"}

modules = ["utils.py",
           "data.py",
           "model.py"]

doc_url = "https://sso0090.github.io/garden/"

git_url = "https://github.com/sso0090/garden/tree/master/"

def custom_doc_links(name): return None
